### ISSUE TITLE
Error: Cannot read property 'key' of null

### ISSUE THREAD

**Issue by gugahoi** [adrai/flowchart.js#65]
Trying to get the basic example to work with no luck.
this is what is in the body of my page:

````html
<div id="diagram">Diagram will be placed here</div>
<script>
  var diagram = flowchart.parse('st=>start: Start:>http://www.google.com[blank]\n' +
                                'e=>end:>http://www.google.com');
  diagram.drawSVG('diagram');
</script>
````

Always get the following error no matter what is inside the `parse()`.

````
TypeError: Cannot read property 'key' of null
    at getDisplaySymbol (http://localhost:3000/include/plugins/flowchart/1.4.2/flowchart.js:1205:28)
    at constructChart (http://localhost:3000/include/plugins/flowchart/1.4.2/flowchart.js:1236:26)
    at Object.chart.drawSVG (http://localhost:3000/include/plugins/flowchart/1.4.2/flowchart.js:1269:11)
````

How do I solve this and what is the least I need to create a flowchart?

**Comment by enterpgup** [comment]
你的语法有问题 在没一个动作后面加 \n
```javascript
var diagram = flowchart.parse('st=>start: 伍|past:>http://www.google.com[blank]\n' +
            'e=>end: Ende:>http://www.google.com\n' +
            'op1=>operation: My Operation|past\n' +
            'op2=>operation: Stuff|current\n' +
            'sub1=>subroutine: My Subroutine|invalid\n' +
            'cond=>condition: Yes or No?|approved:>http://www.google.com\n' +
            'c2=>condition: Good idea|rejected\n' +
            'io=>inputoutput: catch something...|request\n' +
            'st->op1(right)->cond\n' +
            'cond(yes, right)->c2\n' + 
            'cond(no)->sub1(left)->op1\n');
```

**Comment by gugahoi** [comment]
Sorry but I don't speak chinese. What does that mean?

**Comment by hacfi** [comment]
@gugahoi Accordning to google translate he is saying something like the trailing `\n` is causing syntax errors. Hope that is pointing you in the right direction.

**Comment by Wiickette** [comment]
Hello,

A working jsfiddle: https://jsfiddle.net/Wiickette/qLuexh6L/
